name: "run"

on:
  workflow_dispatch:
  schedule:
    - cron: '0/10 * * * 1,2'
    - cron: '0 * * * 3-5'

jobs:
  run:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - run: npm run start
      - name: Push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add dist
          git commit -m "by bot" || echo "no changes"
          git push