name: "run"

on:
  workflow_dispatch:

jobs:
  run:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    defaults:
      shell: bash
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20.x
            cache: npm
        - run: npm ci
        - run: npm run start